name: event-dispatcher

on:
  workflow_run:
    workflows: [ci]
    branches: [dev]
    types:
      - completed

jobs:
  dispatch-event:
    runs-on: ubuntu-latest
    steps:
      - name: Fire Event
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Authorization: Bearer ${{ secrets.REPOSITORY_ACCESS_TOKEN }}" \
            https://api.github.com/repos/ngnijland/repository-dispatch-target-repo/dispatches \
            -d '{"event_type": "dispatch-event"}'
